### ISSUE TITLE
Never getting new refresh tokens

### ISSUE THREAD

**Issue by iamakimmer** [IntuitDeveloper/oauth2-nodejs#2]
Hello,

The documentation states:

> When you request a fresh access token, always use the refresh token returned in the most recent token_endpoint response. Your previous refresh tokens expire 24 hours after you receive a new one.

> Always use the current refresh_token when requesting a new access_token. A new refresh_token is returned and the previous refresh_token is expired. This new refresh_token now has a lifetime of 100 days.

However, when requesting a new access_token never returns a new refresh token, either in the oauth 2.0 playground test page or this sample app.

**Comment by mremondi** [comment]
I'm also seeing the same issue. Is this just an effect of being in sandbox mode?

**Comment by diana-derose** [comment]
Hi @mremondi  - Refresh token gets rotated every 24-26hrs. Try waiting for that period and see if you get a new value back.
