### ISSUE TITLE
Refactor with the official Intuit Oauth module?

### ISSUE THREAD

**Issue by zachweinberg** [IntuitDeveloper/oauth2-nodejs#4]
I was wondering if there were any plans to remake this sample application using the intuit-oauth npm module. It would be very beneficial. Thanks!

**Comment by diana-derose** [comment]
Hi @ZachJames - We might add a few samples using the new library in the future but will retain this one as is for now. You can find the sample using intuit oauth library here-
https://github.com/intuit/oauth-jsclient/tree/master/sample
