### ISSUE TITLE
realmId error

### ISSUE THREAD

**Issue by QuantaCatRob** [IntuitDeveloper/oauth2-nodejs#5]
When I click on API call, I get the following error message.
"error": "No realm ID.  QBO calls only work if the accounting scope was passed!"

All I have changed in what is required in config.json, plus I changed the listening port to 3001 in app.js to match my redirectUri. Thoughts?

**Comment by cyberwombat** [comment]
From looking at the code I think it's simply a broken example. That button (api_call) should not exist on the first option (Sign in w Intuit) since it doesn't connect to an app/company and therefore doesn't get a company ID (the realmID)

**Comment by diana-derose** [comment]
Hi - Thanks for your comments, the sample is meant to show the different flows and how the behavior is while using open id scopes, openId+accounting scope and accounting scope including error scenarios. The idea is one shouldn't expect to make QuickBooks API calls without passing the right scope. We'll update the readme to make it more clear.
